language: go
go: 1.10.1
addons:
  ssh_known_hosts:
  - 111.231.192.70
before_install:
  - openssl aes-256-cbc -K $encrypted_2fac2350cd4f_key -iv $encrypted_2fac2350cd4f_iv
   -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - export $GOPATH
  - ssh root@111.231.192.70 -o StrictHostKeyChecking=no 'cd /home/travis/gopath/src/github.com/abelce/mogo && git pull && go run main.go'